### PR TITLE
chore: Use a single dummy application for testing rails implementation

### PR DESCRIPTION
**Pull request by seuros**
Use a single dummy application to run test in all version.

### CODE REVIEW

**Comment by apotonick** [comment]
We don't need any single `if` to test across all Rails versions? :exploding_head:

**Comment by yogeshjain999** [comment]
Nice refactor 💯 
This proves `cell-rails` neutrality across rails versions 😄

**Comment by seuros** [comment]
I will finish this pr today. Rails 5.2 has a different output in form. Everything else is same.

**Comment by yogeshjain999** [comment]
> I will finish this pr today. Rails 5.2 has a different output in form. Everything else is same.

Yeah, there seems to be an extra `autocomplete` attribute.

**Review by yogeshjain999 — APPROVED** [review]

**Pull request merged**
