### PR TITLE
prevent Forwardable printing warnings in Ruby 2.4+

### LINKED ISSUE #23: Ruby 2.4 warning about delegating a private/protected method `protect_against_forgery?`
`ViewModel#protect_against_forgery?` is delegated to the parent controller here:
https://github.com/trailblazer/cells-rails/blob/a0816159225cff22acdbc27a690cea16b67ae1c3/lib/cell/rails.rb#L50
Ruby 2.4 changes the behavior of `Forwardable` to issue a warning whenever a protected or private method is called via delegation. See https://bugs.ruby-lang.org/issues/12782
Thus, rendering a form inside a cell now prints:
```ruby
/Users/user/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionview-5.0.2/lib/action_view/helpers/url_helper.rb:590:in `token_tag':
#<Module:0x007f899ae87aa8>#protect_against_forgery? at /Users/user/.rbenv/versions/2.4.1/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method UsersController#protect_against_forgery?
```

### PR DESCRIPTION
**Pull request by georgemillo**
Closes #23

### CODE REVIEW

**Comment by georgemillo** [comment]
This should now be fixed on `master`. Let me know if you have any issues.

@apotonick I took the liberty of bumping the version to 0.0.9 - do you think this is worthy of a release?

**Comment by apotonick** [comment]
"Release often, release early." Haha

Thanks!!

**Comment by opti** [comment]
@apotonick would you mind to push v0.0.9 to rubygems?

**Comment by apotonick** [comment]
@georgemillo :pray:

**Comment by georgemillo** [comment]
Whoops haha, I forgot that I have push access to rubygems now. 0.0.9 is now released ;)

**Pull request merged**
