### PR TITLE
Implement view method for rails controller

### PR DESCRIPTION
**Pull request by sveredyuk**
I want to try to add simple method like `view` in controller for render cells like html instead of ActionView. Also thought about such method names as: `render_cell`, `render_view`.

Maybe we also need add some sort of guessing.

``` ruby
def index
  view('product/index', Product.all)
end
```

just:

``` ruby
def index
  view Product.all # and take namespace from controller and cell from action
end
```

What do you think @apotonick ?

### CODE REVIEW

**Comment by apotonick** [comment]
Cool!!! Should it be `view` or should we simply override `render`?

**Comment by sveredyuk** [comment]
@apotonick no, rewriting is bad. I think `view` will be enough.

**Comment by apotonick** [comment]
We could then introduce the same `view` method in `cells-hanami` and `cells-sinatra` (once we implement those gems).

**Comment by sveredyuk** [comment]
@apotonick Sure. The main idea it using cells for application layout totally instead ActionView. 
Now i am doing it like:
```ruby
class MyCell < ViewModel::Cell
   layout :application
end
```

cells/application/application.slim
```ruby
html
  head ...
```

and cells with `yield` i am using for wrapping.

**Comment by apotonick** [comment]
I wouldn't do that, I'd rather use the new layout injection as described here: http://trailblazer.to/gems/cells/getting-started.html#putting-things-together

**Comment by sveredyuk** [comment]
@apotonick it's because this new cool `context`.

**Comment by sveredyuk** [comment]
In on of my projects with TRB I implemented such DSL that allows render cells with layouts from controller:

```ruby
def index
  view 'report#index', reports, layout: :collection do |layout|
    layout.header     'Reports'
    layout.columns sm: 6, md: 9, lg: 6 # bootstrap columns
    layout.header concept('report/cell/action')
end
```

which just convert all this to:
```ruby
  concept('report/cell/index', reports, layout: Cell::Layout::Collection, context: { 
   header: 'Reports', columns: { sm: 6, md: 9, lg: 6 }, header: concept('report/cell/action')
}
```

I found this DSL better than hash key => value, and my teammates also.

@apotonick Does `cells-rails` need my PR ?

**Comment by apotonick** [comment]
That's pretty cool! I think that should be a separate gem, but I thought about something similar, but yours is way cooler.

**Comment by apotonick** [comment]
:heart:

**Comment by sveredyuk** [comment]
@apotonick `cells-punch-rails` gem ? )))

**Comment by sveredyuk** [comment]
`cells-views`

**Comment by apotonick** [comment]
`cells-page` ?

**Pull request closed without merging**
