### PR TITLE
add rails 7 support

### PR DESCRIPTION
**Pull request by ushi-as**

### CODE REVIEW

**Comment by apotonick** [comment]
Hey, cool, thanks! I thiiiink, however, that @seuros decided to have one test directory for all Rails versions, is that true, Abdul?

**Comment by ushi-as** [comment]
> Hey, cool, thanks! I thiiiink, however, that @seuros decided to have one test directory for all Rails versions, is that true, Abdul?

Is this a showstopper? I just used the existing structure... 

The only change i am actually interested in is: https://github.com/trailblazer/cells-rails/pull/63/files#diff-6f2b172fa3858864ce580745717986859610e52b32c6db00331a0b8bb1bfddf2R21

It might be a good idea to just write:

```ruby
if version >= RAILS_5_1
```

Right now i have to override this method in my rspec setup to make it work.

**Comment by apotonick** [comment]
You might be right @ushi-as - maybe we should remove the upper limitation. @seuros @yogeshjain999 ?

**Comment by yogeshjain999** [comment]
Agree, there doesn't seem to be need for the upper limitation and to always override it.

**Comment by seuros** [comment]
we could drop support for rails 5.0, since we are not adding feature in this gem. 
projects with 5.0 can still use a older version of cells-rails.

**Comment by yogeshjain999** [comment]
@ushi-as what steps did you take to add the support (one is obviously to clone existing app) ? could you list them down ? 🍻

**Comment by seuros** [comment]
@apotonick  Approved this PR.

**Review by seuros — APPROVED** [review]

**Comment by yogeshjain999** [comment]
> Do we really need to throw out Rails 5 support? It's a bit messy to test all versions, that's true, but I would vote for keeping this gem as compatible as possible in all versions. And since Trailblazer is a refactoring framework, Rails 5 should be targeted as well.

Makes sense! We should keep the support until some breaking changes are required.

**Comment by jamesbebbington** [comment]
Hi, is pinning on 78a09e6f OK for rails 7.0 support? Or should we wait for a new cells-rails release before upgrading to rails 7.0?

**Comment by apotonick** [comment]
I will look into it today, @jamesbebbington :beer:

**Comment by apotonick** [comment]
It is safe to use `cells-rails-0.1.4` in Rails 7. :+1:

**Comment by jamesbebbington** [comment]
Thanks @apotonick! 

Pinning the gem to 78a09e6f71e1912abf42f1e0f2026b9571a3d024 fixes the test failures we were seeing with `cells-rails-0.1.4` / `rails-7.0`, but I suspect will break dependabot gem updates. If there's still work to be done to keep rails 5 support, might it be possible to push out a pre-release to allow for the best of both worlds?

**Comment by apotonick** [comment]
@jamesbebbington Is the problem that our builds broke? They're running green now, if that was the issue?!

**Pull request merged**
