### PR TITLE
in rails 5.1 ActionController::TestRequest.create needs controller cl…

### PR DESCRIPTION
**Pull request by schorsch**
#26 

love u 2

btw. any help on how to run those tests in the gem locally? I also did not add any rails5.1 gemfile, bcs of this.

### CODE REVIEW

**Comment by apotonick** [comment]
`cd test/rails5.1 && bundle exec rake`

**Comment by schorsch** [comment]
dude, i have no idea what kind of gems are required. Local i have some deprecations and 6 failing spec in rails 5, which i am not going to tackle since i am about to remove all usages of cell(:xy) in favour of plain class "call"s and no rails magic in my cell views anymore

**Comment by tiagoamaro** [comment]
FYI, for anyone having issues with this but want to upgrade to Rails 5.1 anyway, the best approach I found was to monkey patch the `Cell::RailsExtensions::Testing` on a setup file before my test suite. Example:

```ruby
# spec/support/setup/cells.rb

# https://github.com/trailblazer/cells-rails/pull/27
# Monkey patching cells-rails to support Rails 5.1
Cell::RailsExtensions::Testing.module_eval do
  def action_controller_test_request
    ::ActionController::TestRequest.create(controller_class)
  end
end
```

@schorsch, when I tried to use `self.class.controller_class`, it didn't work out. When I checked out what the `self` object was at execution time, noticed it was an example group, not the example per se `#<RSpec::ExampleGroups::BreadcrumbsCell::RenderingShow::Microdata "example at ./spec/cells/breadcrumbs_cell_spec.rb:13">`.

The `self.class.controller_class` call raised an exception  telling me exactly that: `RSpec::Core::ExampleGroup::WrongScopeError: 'controller_class' is not available on an example group`. Thank you very much for this tip 😄!

**Comment by schorsch** [comment]
@tiagoamaro my patch is located at the end of rails_helper.rb:

```ruby

# patch to call ::ActionController::TestRequest.create with controller_class
# TODO Rails 5.1 remove when cells fixed the issue
module Cell
  module RailsExtensions
    module Testing
      def action_controller_test_request
        ::ActionController::TestRequest.create(self.class.controller_class)
      end
    end
  end
end

```

**Comment by schorsch** [comment]
Thanks Nick!

**Pull request merged**
